### ISSUE TITLE
Please merge this PR

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/FZSwiftUtils#1]
[Fix crash due to IKTAddSuperImplementationToClass being stripped](https://github.com/steipete/InterposeKit/pull/30)
This package uses InterposeKit code, after archive packaging it will crash because of the above mentioned problem, please merge this PR manually to fix this problem

**Comment by flocked** [comment]
Implemented the fix provided by [Thomvis](https://github.com/Thomvis). Thanks!
